### ISSUE TITLE
Permissões especiais

### ISSUE THREAD

**Issue by Dani12600000** [Dani12600000/Industries-Manager#12]
Cada utilizador de cada departamento com cada cargo vai ter acessos diferentes ao sistema, isto é apenas para garantir que o utilizador só possa ter acesso a informações que não sejam confidenciais

**Comment by Dani176343** [comment]
Feito a parte das permissões no PMenu
Falta agora só todos os outros, mas eu vou restringir com base nos departamentos que tem acesso

**Comment by Dani176343** [comment]
Não ficou 100% feito, mas vai ser como vai ficar e pronto
