### ISSUE TITLE
Enviar avisos entre diretores e de diretores para seus subordinados

### ISSUE THREAD

**Issue by Dani176343** [Dani12600000/Industries-Manager#6]
Nos avisos eu vou ter que alterar a base de dados significativamente na tabela dos avisos. Vou ter que acrescentar 4 ou 5 campos novos e são:

- [x] ID_Funcionario
- [x] ID_Departamento
- [ ] ID_Diretor (ainda tenho que ver se vou mesmo meter este)
- [x] Titulo (limitar numero de caracteres que podem ser introduzidos para no mínimo 5 e no maximo 55)
- [x] FDFDP (Forma de fim de prazo)

Para que? Eu pretendo usar esses dois para que através de código apenas um dele seja preenchido e assim indique para quem será enviado o aviso.
Por exemplo, eu (Diretor do departamento administrativo) quero enviar um aviso apenas para um funcionário (obviamente no departamento que supervisiono, neste caso o administrativo), vou no formulário próprio dos avisos e escolho uma das 3 opções que são: 
- Funcionário - em que posso mandar para um único funcionário do departamento que é diretor (ou seja escolheria esta opção)
- Departamento - em que vai para todos os subordinados do departamento que é diretor
- Diretor - em que posso mandar para o diretor de outro departamento e assim ele resolver (como por exemplo, vejo um funcionário que não trabalha, então eu como Diretor do departamento administrativo mando um aviso ao Diretor do departamento dos Recursos Humanos, RH, e ai ele faz o que quiser. Como mandar a mensagem que recebeu de mim para os seus subordinados ou resolver isso por ele mesmo)

O FDFDP vai servir para ter 3 tipos:

- Data - parar de mostrar o anuncio assim que chegar a data
- Todos leram - parar de mostrar o anuncio assim que todos tiverem lido (assim que todos no departamento até ao momento tiverem lido os que vierem depois não vão mais lê-lo)
- Nunca - aconteça o que acontecer esse anuncio não para, a não ser por ordem do Diretor

**Comment by Dani176343** [comment]
Menu para os avisos já está a começar a ser desenvolvido
<img width="309" alt="image" src="https://github.com/Dani12600000/Industries-Manager/assets/133104727/17759623-aa9d-4ee2-bd00-54275a188186">

**Comment by Dani176343** [comment]
Depois outra coisa a tratar é o tamanho dos ToolStripMenuItem's
<img width="327" alt="image" src="https://github.com/Dani12600000/Industries-Manager/assets/133104727/da0895dd-c0db-4aca-9a91-6f324696a21d">

**Comment by Dani12600000** [comment]
Base de dados atualizada

**Comment by Dani176343** [comment]
Depois tenho que mudar o tipo de dados do FDFDP da tabela Avisos na base de dados senão linhas como a 166 : `AvisosBindingSource.Current("FDFDP") = FDFDP ` ficam a dar erro
Por enquanto vou dar merge, depois resolvo

**Comment by Dani176343** [comment]
Eu disse que ainda não está closed

**Comment by Dani176343** [comment]
Concluido, agora só testar. Mas vou pular os testes e dar logo merge
