### ISSUE TITLE
Alterações no código dos Departamentos

### ISSUE THREAD

**Issue by Dani176343** [Dani12600000/Industries-Manager#7]
Colocar abreviaturas para Departamentos para funcionar em conjunto com os nomes e descrições dos departamentos. Assim fica mais fácil reconhecer cada departamento com menos caracteres (pode dar jeito para futuras datagridviews). Exemplos de abreviaturas de departamentos, seus nomes e designação do Diretor:

- ADM - Administrativo 
- RH - Recursos Humanos
- TI - Tecnologia da Informação
- Vendas - VD ou VDAS
- Marketing - MKT ou MKTG
- Finanças - FIN ou FINAN
- Contabilidade - CONT ou CONTAB
- Operações - OP ou OPER
- Produção - PROD
- Desenvolvimento de Produtos - DP ou DEPROD
- Compras - CP ou COMP

**Comment by Dani12600000** [comment]
Pronto. Novo campo adicionado, agora falta meter esses exemplos de departamentos para poder usa-los na apresentação
Na Release final irei apagar todos os registos, mas por enquanto fica assim, cheilho de registos

(Nota pessoal para o futuro: fazer uma branch ou marcar uma pull com a base de dados vazia)

**Comment by Dani12600000** [comment]
Agora estou com um pequeno conflito com os registos na minha base de dados, que são

- TI - Tecnologia das informações
- DSI - Desenvolvimento de sistemas de informação
E pelos vistos há mais. Vendo bem vou só colocar alguns departamentos

**Comment by Dani12600000** [comment]
A base de dados já tem os novos campos e os novos registos

**Comment by Dani176343** [comment]
Talvez depois adicionar mais um campo para dizer qual é o departamento ADM e RH no código e assim atribuir aos funcionários desse departamento privilégios extras

**Comment by Dani176343** [comment]
Pensando bem, vai haver uma tabela nova exclusiva para isso e assim atribuir todas as permissões necessárias, provavelmente
um "future-update"

**Comment by Dani176343** [comment]
> Pensando bem, vai haver uma tabela nova exclusiva para isso e assim atribuir todas as permissões necessárias, provavelmente um "future-update"

Mas por enquanto vai ficar sem e vou meter no código a apontar para os departamentos que já existem e depois retiro

**Comment by Dani12600000** [comment]
Acredito que tudo até agora está fechado o resto das melhorias vão ser feitas no issue #12 
Vou agora dar merge
